# SPDX-License-Identifier: Apache-2.0
"""What a request was predicted to cost, and what it actually cost.

Marginalia sizes every request before dispatch. Providers that report usage tell
us what they actually counted. Keeping those two numbers in separate fields —
never merged, never defaulted into each other — is the whole point: the gap
between them is the only evidence available for whether the budgeting model
describes reality.

This is economics, deliberately kept apart from admission. Admission decides
whether a request may proceed and is a safety boundary; this decides what to
report afterwards. They share observations, not contracts, and nothing here may
feed back into a budget decision.

Initial draft of the dataclasses generated by a local model; reviewed and
corrected (see module history in the campaign notes).
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Literal


@dataclass(frozen=True)
class EstimatedUsage:
    """What Marginalia computed before dispatch."""

    prompt_tokens: int


@dataclass(frozen=True)
class ObservedUsage:
    """What the provider reported afterwards.

    Every field is optional because many providers report nothing. Absent is
    `None` and never `0`: a zero would silently claim a free request and would
    corrupt any aggregate built on top of it.
    """

    prompt_tokens: int | None = None
    completion_tokens: int | None = None
    reasoning_tokens: int | None = None
    total_tokens: int | None = None
    cost_usd: float | None = None
    source: Literal["provider_reported", "normalized", "unavailable"] = "provider_reported"

    @property
    def reported(self) -> bool:
        """True when the provider returned anything usable at all."""
        return any(
            value is not None
            for value in (
                self.prompt_tokens,
                self.completion_tokens,
                self.reasoning_tokens,
                self.total_tokens,
                self.cost_usd,
            )
        )


@dataclass(frozen=True)
class RequestAccounting:
    """One request's estimated and observed cost, side by side."""

    provider_id: str
    model_id: str
    # Absent when the request did not go through a bounded budget: what a call
    # cost is worth recording either way, but only a budgeted request has an
    # estimate to be measured against.
    estimated: EstimatedUsage | None
    observed: ObservedUsage
    latency_ms: float

    @property
    def prompt_delta(self) -> int | None:
        """Observed minus estimated prompt tokens, or None if unreported.

        This is the number that makes `provider_overhead_tokens` measurable
        instead of assumed.
        """
        if self.observed.prompt_tokens is None or self.estimated is None:
            return None
        return self.observed.prompt_tokens - self.estimated.prompt_tokens

    def to_dict(self) -> dict[str, Any]:
        """Flat and JSON-safe, with the two sources kept prefixed and distinct."""
        return {
            "provider_id": self.provider_id,
            "model_id": self.model_id,
            "latency_ms": round(self.latency_ms, 1),
            "estimated_prompt_tokens": (
                None if self.estimated is None else self.estimated.prompt_tokens
            ),
            "observed_prompt_tokens": self.observed.prompt_tokens,
            "observed_completion_tokens": self.observed.completion_tokens,
            "observed_reasoning_tokens": self.observed.reasoning_tokens,
            "observed_total_tokens": self.observed.total_tokens,
            "observed_cost_usd": self.observed.cost_usd,
            "observed_source": self.observed.source,
            "prompt_delta": self.prompt_delta,
        }


def _number(source: Any, key: str) -> int | float | None:
    """One numeric field, or None. Booleans are not numbers."""
    if not isinstance(source, dict):
        return None
    value = source.get(key)
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        return None
    return value


def _tokens(source: Any, key: str) -> int | None:
    """A token count. Providers occasionally report these as floats."""
    value = _number(source, key)
    if value is None or value < 0:
        return None
    return int(value)


def observed_from_provider_usage(usage: Any) -> ObservedUsage:
    """Read an OpenAI/OpenRouter-shaped usage object without trusting it.

    Anything missing, malformed, or the wrong type becomes None. This is called
    on provider output, so it must not raise for any input at all — a billing
    field is never a reason to fail a request that already succeeded.
    """
    details = usage.get("completion_tokens_details") if isinstance(usage, dict) else None
    cost = _number(usage, "cost")
    return ObservedUsage(
        prompt_tokens=_tokens(usage, "prompt_tokens"),
        completion_tokens=_tokens(usage, "completion_tokens"),
        reasoning_tokens=_tokens(details, "reasoning_tokens"),
        total_tokens=_tokens(usage, "total_tokens"),
        cost_usd=None if cost is None or cost < 0 else float(cost),
        source="provider_reported",
    )


def observed_from_normalized_usage(usage: Any) -> ObservedUsage:
    """Read legacy normalized counters without claiming raw provider data."""
    prompt = _tokens(usage, "prompt_tokens")
    completion = _tokens(usage, "completion_tokens")
    total = _tokens(usage, "total_tokens")
    if not any(value for value in (prompt, completion, total)):
        return ObservedUsage(source="unavailable")
    return ObservedUsage(
        prompt_tokens=prompt,
        completion_tokens=completion,
        total_tokens=total,
        source="normalized",
    )
